# Generated by Django 5.2.16 on 2026-07-13 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_description_original', models.TextField()),
                ('illness_description_translated', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('specialization', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Gynecology', 'Gynecology'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Other', 'Other')], default='General Medicine', max_length=100)),
                ('is_all_rounder', models.BooleanField(default=False, help_text='Check if the doctor handles all basic diseases')),
                ('solved_patients', models.PositiveIntegerField(default=0, help_text='Number of patients successfully treated')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of medical experience')),
                ('languages_spoken', models.JSONField(blank=True, default=list, help_text='List of languages the doctor speaks')),
                ('bio', models.TextField(blank=True, default='', help_text='Short biography or professional summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('severity_weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['-severity_weight', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('computed_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='care.case')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='care.doctor'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('source_language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati')], default='Hindi', max_length=20)),
                ('destination_language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati')], default='English', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='care.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='care.patient'),
        ),
    ]
