# Generated by Django 5.2.16 on 2026-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='destination_language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='source_language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=20),
        ),
    ]
