# Generated by Django 4.2.30 on 2026-10-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_alter_patient_destination_language_and_more'),
    ]

    operations = [
    ]
